#security:
#  basic:
#    enabled: false

#management:
#  security:
#    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

#ribbon: # <---NEW SECTION
#  IsSecure: false
  
eureka: # <--- ADD NEW SECTION
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}
      
--- # <--- ADD NEW DOCUMENT

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}
