# Common values for all micro services.
logging:
  level:
    io:
      pivotal: DEBUG
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}
  client:    # This will define the Eureka Discovery uri for all micro services cf set-env product-service (set for all ms) DISCOVERY_URL service-registry-penecontemporaneous-urgency.local.pcfdev.io
    serviceUrl:
      defaultZone: http://${DISCOVERY_URL:http://127.0.0.1:8761}/eureka/

#---  # <--- ADD NEW DOCUMENT

#spring:
#  profiles: dev
#eureka:
#  client:    
 #   serviceUrl:
   #   defaultZone: http://service-registry-penecontemporaneous-urgency.local.pcfdev.io/eureka/
